<a href="https://colab.research.google.com/github/DrsimpleMugo/Pneumonia-Detection-in-chest-Xray-Images/blob/main/Chest_XrayDeyloyment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install flask-ngrok

In [ ]:
cd /content/drive/MyDrive/ChestXrayDeployment


/content/drive/MyDrive/ChestXrayDeployment


In [ ]:
import flask
from flask import Flask, render_template, request
import numpy as np
from flask_ngrok import run_with_ngrok
from keras.preprocessing. image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications import inception_v3
from keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.models import load_model
import warnings
warnings.filterwarnings('ignore')
print('successful')

successful


In [ ]:
from __future__ import division,print_function
import numpy as np
import tensorflow as tf
import sys
import os
import glob
import re

# This block of code is used if you are going to deploy your model in Nvidi GPU if you don't have it then you can skip these codes

from tensorflow.compat.v1 import ConfigProto
from tensorflow.python.keras.backend import set_session


tf.keras.backend.clear_session()
config = tf.compat.v1.ConfigProto(gpu_options = 
                         tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.9)
)
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(session)

# Upto here 


from tensorflow.keras.applications.inception_v3 import preprocess_input, decode_predictions
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing import image

from flask import Flask,redirect,url_for,request,render_template
from werkzeug.utils import secure_filename


# Define a Flask App
app = Flask(__name__)
run_with_ngrok(app)

# Load model
# graph = tf.get_default_graph()
model_path = 'Pneumonia.h5'
model = load_model(model_path)
#model.summary()
#model._make_predict_function()  #Necessary for imagenet weights 
# If model._make_predict_funciton() throws you error then you can discard this line and comment it.


def model_predict(img_path,model):
  img = image.load_img(img_path,target_size=(224,224))
  x = image.img_to_array(img)
  x = np.expand_dims(x,axis=0)
  x = x/255
  x = preprocess_input(x)
  predictions = Dense(2, activation='softmax')(x)
  preds = model.predict(x)
  return preds


@app.route('/',methods = ['GET'])
def index():
	# Main page
	return render_template('./index.html')


@app.route('/',methods=["POST","GET"])
def upload():
  if request.method=='POST':
    f = request.files['file']
    print(f)
    file_path = "/content/drive/MyDrive/ChestXrayDeployment/templates/images" + f.filename
    f.save(file_path)
    preds = model_predict(file_path,model)
    print(preds)

    result = np.argmax(preds, axis = 1)

    if result == 0:
      result = 'Infected'
    else:
      result = 'Normal'


    return render_template('./predict.html',result=result)
  else:
    return render_template('./index.html')

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://8f60a5c087a7.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [16/Aug/2021 07:01:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:01:22] "GET /static/css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:01:24] "GET /favicon.ico HTTP/1.1" 404 -


<FileStorage: 'diseased.jfif' ('image/jpeg')>
[[9.9996245e-01 3.7565125e-05]]


127.0.0.1 - - [16/Aug/2021 07:01:52] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:01:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:14:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:14:44] "POST / HTTP/1.1" 400 -


<FileStorage: 'IM-0050-0001.jpeg' ('image/jpeg')>


127.0.0.1 - - [16/Aug/2021 07:14:53] "POST / HTTP/1.1" 200 -


[[0.9959186  0.00408139]]


127.0.0.1 - - [16/Aug/2021 07:16:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:16:34] "POST / HTTP/1.1" 200 -


<FileStorage: 'diseased.jfif' ('image/jpeg')>
[[9.9996245e-01 3.7565125e-05]]


127.0.0.1 - - [16/Aug/2021 07:16:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:16:55] "POST / HTTP/1.1" 400 -
127.0.0.1 - - [16/Aug/2021 07:16:57] "POST / HTTP/1.1" 400 -
127.0.0.1 - - [16/Aug/2021 07:16:58] "POST / HTTP/1.1" 400 -


<FileStorage: 'IM-0046-0001.jpeg' ('image/jpeg')>


127.0.0.1 - - [16/Aug/2021 07:17:01] "POST / HTTP/1.1" 200 -


[[9.9987459e-01 1.2540231e-04]]


127.0.0.1 - - [16/Aug/2021 07:20:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 07:21:21] "POST / HTTP/1.1" 200 -


<FileStorage: '.hgdd.PNG' ('image/png')>
[[9.9922776e-01 7.7225192e-04]]
